Fix compile failure in OfflineVideoSource.
This resolves a compile-time conflict between changes to EmeManager
(commit a4e9bc3, merge of pull request #36) and OfflineVideoSource
(commit 18a843e), merged together in f204c8d to create a compiler
error:

offline_video_source.js:81: ERROR - actual parameter 1 of EmeManager
                                    does not match formal parameter
found   : shaka.player.OfflineVideoSource
required: shaka.player.Player
            new shaka.media.EmeManager(this, fakeVideoElement, this);

Change-Id: I6b263ef0e443bb305f96928b0d0c5019056d7014