Issue 1030: Fix broken Typescript type declarations
Partially fixes #1030. The issue was created to track a problem using
Shaka from a Typescript project. Inside the issue, a fix was contributed
by @alexandercerutti, although it was acknowledged that the fix was not
a complete fix. Event types are still missing, for instance. Having said
that, it seems the main reason that @alexandercerutti's partial fix
wasn't applied is that @joeyparrish expressed a desire for a small
Typescript sample to be added as an automated test to verify that this
works.

Changes
1) Modified generateTsDefs.py to apply the partial fix by
@alexandercerutti.
2) While testing, I discovered that the Windows build produces a broken
.d.ts, because the bytes on Windows (b'?_?.clutz.') are different
than Linux (b'\xe0\xb2\xa0_\xe0\xb2\xa0.clutz.'). Fixed by adding a
second replace pattern for Windows. Since the two are mutually
exclusive, I just run them serially without condition.
3) While verifying, I noticed some unreplaced clutz namespaces. These
occur because instead of ".clutz." the pattern is ".clutz ". I looked
into a couple, they seem to have been supplied because the Closure
compiler lacks declarations. Added Linux and Windows replacement lines
to assign these to the "shakaExterns" namespace.
4) Added a simple Typescript compilation test. I structured the
tsconfig.json to look like a typical usage case where shaka-player is
imported as a node module. Note that if we set skipLibCheck to false,
this leads to the errors described in Issue #3185, eg. error TS2694:
Namespace 'google.ima.dai.api' has no exported member 'StreamRequest'
(also mentioned in Issue #1030). NOTE that when this test fails, I
couldn’t figure out how to get the compiler output on-screen, so instead
I provide instructions for re-running the test interactively, which will
produce the error on-screen.

Testing Procedure
1) python build/test.py. Confirm pass.
2) Verify that some of the previously unreplaced clutz namespaces, such
as ಠ_ಠ.clutz.AirPlayEvent, are no longer under the ಠ_ಠ.clutz prefix
and instead are under the shakaExterns namespace, and
that you can compile successfully.
3) Repeat both of the above steps under both Linux and Windows. Confirm
that the produced .d.ts files differ only in the comments, where the
source file path is stated.