fix: Add optional content workaround to force ENCA.ChannelCount to 2 for EAC-3 Audio init segments (#8517)
In short, we've discovered a packaging issue on some of our streams
where the ChannelCount field of the enca box contains an invalid value
of 7. According to the dolby spec (and confirmed by their validator):
- This field should always be 2
- This field should be ignored by the decoder/user agent

From talking to the Dolby folks, it seems that some devices erroneously
do not ignore this value. Chromecast is one of said devices. Playing
back an EAC-3 audio track on Chromecast packaged this way causes an
immediate fatal decoding failure. -- rewriting that box content client
side to force a value of 2 fixes playback without any other issues.

This fix will take the init segment (if it's audio and the workaround is
enabled), and replace the ChannelCount with 2 if and only if the
original audio codec was EC3.

Given that these streams were packaged by Bento4, I figure it may be
possible for this to happen for others. The workaround is generic enough
that I think it's reasonable to have as an optional content workaround
in Shaka.

Here's some output from the Dolby validator indicating the requirement
here:
```
ERROR: For an [EC3] stream, in MP4 EC3SampleEntryBox, the "ChannelCount" must set to 2.  (ETSI TS 102 366 V1.4.1 (2017-09) F.5.1)
```

---------

Co-authored-by: Nicholas Crast <nick.crast@nbcuni.com>
Co-authored-by: Álvaro Velad Galván <ladvan91@hotmail.com>